### ISSUE TITLE
Installer must copy jsmmp jar into oxauth custom libs

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/casa#106] opened 2019-12-21 13:48 UTC
In addition to twilio jar we must also include jsmpp jar

In the paackage, it is available at `/opt/dist/gluu`

Adjust oxauth.xml as well so this file is included, like `<Set name="extraClasspath">./custom/libs/twilio-7.17.0.jar,./custom/libs/jsmpp-2.3.7.jar</Set>`

**Comment by mbaser** [comment] 2019-12-24 14:35
Implemented by commit https://github.com/GluuFederation/casa/commit/0685d7991370e381c8cf641bb88b6b9b7904abdb

**Comment by jgomer2001** [comment] 2019-12-27 21:42
@mbaser This is oxauth.xml after installation:

```
<?xml version="1.0"  encoding="ISO-8859-1"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_0.dtd">

<Configure class="org.eclipse.jetty.webapp.WebAppContext">
	<Set name="contextPath">/oxauth</Set>
	<Set name="war">
		<Property name="jetty.webapps" default="." />/oxauth.war
	</Set>
	<Set name="extractWAR">true</Set>

	<Set name="extraClasspath">./custom/libs/twilio-7.17.0.jar</Set>
	<Set name="extraClasspath">./custom/libs/jsmpp-2.3.7.jar</Set>
</Configure>
```

It degenerates in 
```
caused by: Traceback (most recent call last):
  File "twilio_sms.py", line 17, in <module>
ImportError: No module named twilio

	at org.python.core.Py.ImportError(Py.java:334)
```

proper xml syntax is as suggested in issue description (separated by comma)

**Comment by mbaser** [comment] 2019-12-28 13:19
@jgomer2001 Please test latest version and close this issue if it modifies oxauth.xml as intended.

**Closed** 2020-01-14 16:39 UTC
Labels: enhancement
